CollegeConnected/Controllers/ImportController.cs
using System;
using System.Linq;
using System.Net.Mime;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Web.Security;
using CollegeConnected.Imports;
using CollegeConnected.Models;

namespace CollegeConnected.Controllers
{
    public class ImportController : Controller
    {
        public ActionResult StudentColumnOptions()
        {
            if (isAuthenticated())
            {
                if (ImportManager.IsGettingColumnOptions())
                {
                    try
                    {
                        ImportManager.PrepareHeaders();
                    }
                    catch (Exception ex)
                    {
                        return RedirectToAction(
                            "UploadError",
                            new {uploadError = ex.Message, returnAction = "StartStudent"});
                    }

                    return View(MvcApplication.CurrentImport.columnConfiguration);
                }

                return RedirectToAction(ImportManager.CurrentView());
            }
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public ActionResult StudentColumnOptions(StudentImportColumnConfigurationModel id)
        {
            if (ImportManager.IsGettingColumnOptions())
            {
                if (!ImportManager.AddColumnConfiguration(id))
                {
                    ModelState.AddModelError(string.Empty, MvcApplication.CurrentImport.ErrorMessage);

                    id.SelectionCollection =
                        ((StudentImportColumnConfigurationModel) MvcApplication.CurrentImport.columnConfiguration)
                        .SelectionCollection;

                    return View(id);
                }

                ImportManager.KickOffImport();

                return RedirectToAction(ImportManager.CurrentView());
            }

            return RedirectToAction(ImportManager.CurrentView());
        }

        public void DownloadReject(int id)
        {
            var cd = new ContentDisposition {FileName = "rejectfile.xlsx", Inline = false};
            Response.Clear();
            Response.AppendHeader("Content-Disposition", cd.ToString());
            Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            using (var db = new CollegeConnectedDbContext())
            {
                var rejectBytes = db.ImportResults.Single(m => m.Id == id).RejectFile;
                Response.BinaryWrite(rejectBytes);
            }

            Response.End();
        }

        [HttpPost]
        public async Task<ActionResult> GetProgress()
        {
            ProgressStatus result = null;
            await Task.Run(() => { result = CollegeConnectedImporterBase.GetStatus(); });
            return Json(result);
        }


        public ActionResult Progress()
        {
            return View();
        }

        public ActionResult StartStudent()
        {
            if (isAuthenticated())
            {
                if (ImportManager.IsImportReady())
                {
                    MvcApplication.CurrentImport = new StudentImport();

                    return View();
                }

                return RedirectToAction(ImportManager.CurrentView());
            }
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public ActionResult StartStudent(StudentImportOptionsModel id)
        {
            if (isAuthenticated())
            {
                if (ImportManager.IsImportReady())
                {
                    if (ModelState.IsValid)
                    {
                        if (ImportManager.InitializeImport(id))
                            return RedirectToAction(ImportManager.CurrentView());

                        ModelState.AddModelError("import", MvcApplication.CurrentImport.ErrorMessage);
                    }

                    return View();
                }

                return RedirectToAction(ImportManager.CurrentView());
            }
            return RedirectToAction("Index", "Home");
        }

        public ActionResult UploadError(string uploadError, string returnAction)
        {
            ViewBag.ErrorString = $"There was an error uploading the file: {uploadError}";
            ViewBag.ActionName = returnAction;

            return View();
        }

        public ActionResult ViewImportFiles()
        {
            return View();
        }

        private bool isAuthenticated()
        {
            var authCookie = Request.Cookies[FormsAuthentication.FormsCookieName];
            if (authCookie != null)
            {
                var ticket = FormsAuthentication.Decrypt(authCookie.Value);

                if (ticket != null)
                    return true;
            }
            return false;
        }
    }
}

CollegeConnected/Views/Import/Progress.cshtml
@using CollegeConnected.Models
<h2>Import Progress</h2>

<div id="importStatusLabel">
</div>
<div id="importedItemsLabel" style="display: none">
</div>
<div id="importedErrorItemsLabel">
</div>
<br/>
<br/>
<div id="downloadRejectFileButton" class="errorText">
    Download Reject File
</div>
<br/>
<br/>
<br/>

<div id="progressbar" class="progressbar">
    <div id="progress-label" class="progress-label ">Loading...</div>
</div>

<script type="text/javascript">
    var inverse = true;
    var currentMode = 0;
    var lineCount = -1;
    var convertCount = 0;
    var convertErrorCount = 0;
    var convertTotal = 0;
    var importCount = 0;
    var importErrorCount = 0;
    var importTotal = 0;
    var fileId;

    $("#downloadRejectFileButton")
        .click(function() {
            if (fileId) {
                window.location = "DownloadReject?id=" + fileId;
            }
        });
    $(document)
        .ready(function() {
            $("#progressbar").progressbar({ change: updateProgressBarText });
            $("#downloadRejectFileButton").button({ text: "Download Reject File", icons: { primary: "ui-icon-disk" } });
            $("#downloadRejectFileButton").hide();
            getStatus();
        });

    function getStatus() {
        $.ajax({
            url: "GetProgress",
            data: JSON.stringify({ "CurrentRecordCount": lineCount }),
            type: 'POST',
            contentType: 'application/json',
            success: recieved_data,
            error: recieve_error
        });
    }

    function recieved_data(returnData) {
        if (returnData == null || returnData.Status == 0)
            window.location.href = '@Url.Action("ViewImportFiles", "Import")';

        convertTotal = returnData.ExpectedToConvert;
        convertCount = returnData.ConvertedRecords;
        convertErrorCount = returnData.ConvertErrors;
        importTotal = returnData.ConvertedRecords;
        importCount = returnData.ImportedRecords;
        importErrorCount = returnData.ImportErrors;
        fileId = returnData.FileId;

        if (fileId) {
            $("#downloadRejectFileButton").show();
        }
        if (returnData.Status >= parseInt('@((int) ImportProgressTypeEnum.ImportCompleted)')) {
            currentMode = 3;
        } else if (returnData.Status >= parseInt('@((int) ImportProgressTypeEnum.UploadingResults)')) {
            currentMode = 2;
        } else if (returnData.Status >= parseInt('@((int) ImportProgressTypeEnum.ConversionCompleted)')) {
            currentMode = 1;
        } else {
            currentMode = 0;
        }

        if (currentMode == 0) {
            //Converting Data
            var progress = ((convertCount + convertErrorCount) / convertTotal) * 100;
            $("#importStatusLabel").text("Import Status: Importing Data");
        } else if (currentMode == 1) {
            //Importing Data
            var progress = ((importCount + importErrorCount) / importTotal) * 100;
            $("#importStatusLabel").text("Import Status: Importing Data");
        } else if (currentMode == 2) {
            //Uploading Data
            var progress = 100;
            $("#importStatusLabel").text("Import Status: Uploading Import File");
        } else if (currentMode == 3) {
            //Import Complete
            var progress = 100;
            $("#importStatusLabel").text("Import Status: Complete");
            updateProgressBarText();
        }

        if (currentMode == -1) {
            //Error State
            progress = 0;
        } else if (currentMode != 3) {
            setTimeout(getStatus, 1000);
        }
        if (currentMode == 3) {
            $("#progressbar").progressbar({ value: progress });
        } else {
            $("#progressbar").progressbar({ value: false });
        }

        var totalErrorCount = importErrorCount + convertErrorCount;

        $("#progressbar > div").removeClass("ui-widget-header");
        if (totalErrorCount > 0) {
            $("#progressbar > div").addClass("progress-failure");
            $("#importedItemsLabel").addClass("errorText");
            $("#importedErrorItemsLabel").addClass("errorText");
        } else {
            $("#progressbar > div").addClass("progress-success");
            $("#importedItemsLabel").addClass("successText");
            $("#importedErrorItemsLabel").addClass("successText");
        }

        $("#importedItemsLabel").text("Items Imported: " + importCount);
        $("#importedErrorItemsLabel").text("Errors during Import: " + totalErrorCount);
    }

    function updateProgressBarText() {
        var progressbar = $("#progressbar");
        var progressLabel = $("#progress-label");

        if ($("#importStatusLabel:contains(Convert)").length) {
            progressLabel.text("Converting in progress...");
        } else if ($("#importStatusLabel:contains(Importing)").length) {
            progressLabel.text("Importing in progress...");
        } else if ($("#importStatusLabel:contains(Uploading)").length) {
            progressLabel.text("Uploading Import File...");
        } else if ($("#importStatusLabel:contains(Complete)").length) {
            progressLabel.text("Import Complete");
        }
    }

    function recieve_error(jqXHR, textStatus, errorThrown) {
        alert(textStatus);
        alert(errorThrown);
    }

    function sortRows() {
        //For Original Script
        //var parentTable = $(this).closest("table");

        var parentTable = $("#importResults");
        var thIndex = $(this).index();
        var tdList = parentTable.find("td")
            .filter(function() {
                return $(this).index() == thIndex && !$(this).hasClass("sortableColumn");
            });
        if (thIndex == 0) {
            tdList.sort(function(a, b) {
                return parseInt($.text([a])) > parseInt($.text([b]))
                    ? inverse ? -1 : 1
                    : inverse ? 1 : -1;

            });
        } else {
            tdList.sort(function(a, b) {
                return $.text([a]) > $.text([b])
                    ? inverse ? -1 : 1
                    : inverse ? 1 : -1;

            });
        }

        //Needed for original since it had a header row
        //var headerRow = parentTable.find("tr").first();

        parentTable.empty();

        //Needed for original since it had a header row
        //parentTable.append(headerRow);

        $(tdList)
            .each(function(index, value) {
                parentTable.append(value.parentNode);
            });

        inverse = !inverse;

        //Needed for original for header row rebinding
        //$(".sortableColumn").on("click", sortRows);
    }
</script>

@section Scripts {
    @Scripts.Render("~/Scripts/jquery-ui-1.10.3.custom.min.js")
}@section Styles {
     @Styles.Render("~/Content/jquery-ui-1.10.3.custom.min.css")
 }

CollegeConnected/Views/Import/StartStudent.cshtml
@model CollegeConnected.Models.StudentImportOptionsModel

<h2>Constituent Import</h2>

<h3>Please select your import options and click "Column Options"</h3>

@using (Html.BeginForm("StartStudent", "Import", FormMethod.Post, new {enctype = "multipart/form-data"}))
{
    <fieldset style="width: 480px">
        <legend>Import Options</legend>
        <p>
            @Html.LabelFor(m => m.File)
        </p>
        <p style="margin-left: 15px">
            @Html.TextBoxFor(m => m.File, new {type = "file"})
        </p>
        <p>
            @Html.ValidationSummary()
        </p>
        <p>
            <input style="float: right" type="submit" value="Column Options">
        </p>
    </fieldset>
}

CollegeConnected/Views/Import/StudentColumnOptions.cshtml
@model CollegeConnected.Models.StudentImportColumnConfigurationModel

<h2>Import Column Mapping</h2>
@using (Html.BeginForm())
{
    <table style="border-spacing: 0px">
        <tr>
            @for (var columnIndex = 0; columnIndex < Model.Configuration.Count; columnIndex++)
            {
                <th class="ImportColumn columnInfo_@columnIndex" style="width: 300px">
                    @Html.CheckBoxFor(m => m.Configuration[columnIndex].Include, new {@class = "includeCheckBox", data_id = columnIndex})
                    @Html.LabelFor(m => m.Configuration[columnIndex].Include)<br/>
                    @Model.Configuration[columnIndex].Name<br/>
                    @Html.HiddenFor(m => m.Configuration[columnIndex].Name)
                    @Html.DropDownListFor(m => m.Configuration[columnIndex].Type, Model.SelectionCollection, new {@class = "mappingType", style = "width:150px", data_id = columnIndex})<br/>
                </th>
            }
        </tr>
        <tr>
            @for (var columnIndex = 0; columnIndex < Model.Configuration.Count; columnIndex++)
            {
                if (Model.Configuration[columnIndex].sampleRowData.Count > 0)
                {
                    <td class="ImportColumn columnInfo_@columnIndex" style="text-align: center">
                        @Html.HiddenFor(m => m.Configuration[columnIndex].sampleRowData[0])
                        @Model.Configuration[columnIndex].sampleRowData[0]
                    </td>
                }
            }
        </tr>
        <tr>
            @for (var columnIndex = 0; columnIndex < Model.Configuration.Count; columnIndex++)
            {
                if (Model.Configuration[columnIndex].sampleRowData.Count > 1)
                {
                    <td class="ImportColumn columnInfo_@columnIndex" style="text-align: center">
                        @Html.HiddenFor(m => m.Configuration[columnIndex].sampleRowData[1])
                        @Model.Configuration[columnIndex].sampleRowData[1]
                    </td>
                }
            }
        </tr>
        <tr>
            @for (var columnIndex = 0; columnIndex < Model.Configuration.Count; columnIndex++)
            {
                if (Model.Configuration[columnIndex].sampleRowData.Count > 2)
                {
                    <td class="ImportColumn columnInfo_@columnIndex" style="text-align: center">
                        @Html.HiddenFor(m => m.Configuration[columnIndex].sampleRowData[2])
                        @Model.Configuration[columnIndex].sampleRowData[2]
                    </td>
                }
            }
        </tr>
    </table>
    @Html.ValidationSummary()
    @Html.HiddenFor(m => m.SelectionCollection)
    <input type="submit" value="Submit"/>
}
<script type="text/javascript">
    var columnConfiguration = $.parseJSON('@Html.Raw(Json.Encode(Model.Configuration))');
    $(".includeCheckBox")
        .change(function() {
            var id = $(this).data("id");

            if ($(this).prop("checked")) {
                $(".columnInfo_" + id).removeClass("selectedImportColumn");
                $(".columnInfo_" + id).addClass("ImportColumn");
            } else {
                $(".columnInfo_" + id).addClass("selectedImportColumn");
                $(".columnInfo_" + id).removeClass("ImportColumn");
            }
        });

</script>

CollegeConnected/Views/Import/UploadError.cshtml
@{
    ViewBag.Title = "UploadError";
}

<h2>Error parsing file</h2>
<div>@ViewBag.ErrorString</div>
<div>
    <a href="@ViewBag.ActionName">Back to Import</a>
</div>

CollegeConnected/Views/Import/ViewImportFiles.cshtml
@{
    ViewBag.Title = "ViewImportFiles";
}

<h2>ViewImportFiles</h2>