CollegeConnected/Models/Settings.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace CollegeConnected.Models
{
    public class Settings
    {
        [Key]
        public Guid Id { get; set; }

        [EmailAddress]
        public string EmailUsername { get; set; }

        [DataType(DataType.Password)]
        public string EmailPassword { get; set; }

        public string EmailHostName { get; set; }

        [StringLength(5)]
        [RegularExpression("([1-9][0-9]*)", ErrorMessage = "Port must contain only numbers")]
        public string EmailPort { get; set; }

        public string EventEmailMessageBody { get; set; }
    }
}

CollegeConnected/Controllers/SettingsController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using System.Web.Security;
using CollegeConnected.DataLayer;
using CollegeConnected.Models;

namespace CollegeConnected.Controllers
{
    public class SettingsController : Controller
    {
        private readonly UnitOfWork db = new UnitOfWork();
        private readonly BaseController sharedOperations = new BaseController();

        public ActionResult Configuration()
        {
            if (sharedOperations.IsAuthenticated(Request.Cookies[FormsAuthentication.FormsCookieName]))
            {
                if (db.SettingsRepository.dbSet.Any())
                {
                    var settings = db.SettingsRepository.GetUser();
                    return View(settings);
                }
                return View();
            }
            return RedirectToAction("Index", "Home");
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Configuration([Bind(
            Include =
                "Id,EmailUsername,EmailPassword,EmailHostName,EmailPort,EventEmailMessageBody"
        )] Settings settings)
        {
            if (!db.SettingsRepository.dbSet.Any())
            {
                settings.Id = Guid.NewGuid();
                db.SettingsRepository.Insert(settings);
                db.Save();
            }
            else
            {
                db.SettingsRepository.Update(settings);
                db.Save();
            }
            return RedirectToAction("Admin", "Home");
        }
    }
}

CollegeConnected/Views/Settings/Configuration.cshtml
@model CollegeConnected.Models.Settings

@{
    ViewBag.Title = "Configuration";
}

<h2>Email Settings</h2>

@using (Html.BeginForm("Configuration", "Settings", FormMethod.Post, new { autocomplete = "off" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr/>
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.EmailUsername, "Outgoing Email Address", new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailUsername, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.EmailUsername, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailPassword, "Outgoing Email Password", new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailPassword, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.EmailPassword, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailHostName, "Outgoing Email Host Name", new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailHostName, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.EmailHostName, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailPort, "Outgoing Email Port", new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailPort, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.EmailPort, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventEmailMessageBody, "Event Email Message Body", new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.TextAreaFor(x => x.EventEmailMessageBody, 10, 55, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.EventEmailMessageBody, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default"/>
            </div>
        </div>
    </div>
}