CollegeConnected/Models/Constituent.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace CollegeConnected.Models
{
    public class Constituent
    {
        [Key]
        public Guid StudentId { get; set; }

        public string StudentNumber { get; set; }

        [Required]
        [StringLength(50, MinimumLength = 2)]
        public string FirstName { get; set; }

        [StringLength(50)]
        public string MiddleName { get; set; }

        [Required]
        [StringLength(50, MinimumLength = 2)]
        public string LastName { get; set; }

        [Required]
        public string Address1 { get; set; }

        public string Address2 { get; set; }

        [Required]
        [StringLength(5)]
        [RegularExpression("([1-9][0-9]*)", ErrorMessage = "Zip Code must contain only numbers")]
        public string ZipCode { get; set; }

        [Required]
        [StringLength(50)]
        public string City { get; set; }

        [Required]
        public State State { get; set; }

        [Phone]
        public string PhoneNumber { get; set; }

        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        public string FirstGraduationYear { get; set; }

        public string SecondGraduationYear { get; set; }
        public string ThirdGraduationYear { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public DateTime BirthDate { get; set; }

        public DateTime UpdateTimeStamp { get; set; }

        [Required]
        public ConstituentType ConstituentType { get; set; }

        [Required]
        public bool AllowCommunication { get; set; }

        public bool HasAttendedEvent { get; set; }
        public int EventsAttended { get; set; }
    }
}

CollegeConnected/Controllers/BaseController.cs
using System;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using CollegeConnected.DataLayer;

namespace CollegeConnected.Controllers
{
    public class BaseController : Controller
    {
        private readonly UnitOfWork db = new UnitOfWork();

        public SelectList GenerateGradYearList()
        {
            return new SelectList(Enumerable.Range(1940, 100).Select(x =>
                new SelectListItem
                {
                    Text = x.ToString(),
                    Value = x.ToString()
                }), "Value", "Text");
            ;
        }

        public bool IsAuthenticated(HttpCookie cookie)
        {
            if (cookie != null)
            {
                var ticket = FormsAuthentication.Decrypt(cookie.Value);

                if (ticket != null)
                    return true;
            }
            return false;
        }

        public void ExportToCsv(Guid? id, string exportType)
        {
            var sw = new StringWriter();

            sw.WriteLine("\"Student Number\",\"First Name\",\"Middle Name\",\"Last Name\",\"Address1\"," +
                         "\"Address2\",\"Zip Code\",\"City\",\"State\",\"Phone Number\",\"Email\"," +
                         "\"Birthday\",\"First Grad Year\",\"Second Grad Year\",\"Third Grad Year\",\"Constiuent Type\",\"Allow Communication\"");
            Response.ClearContent();
            Response.AddHeader("content-disposition",
                "attachment;filename=ExportedConstituents_" + DateTime.Now + ".csv");
            Response.ContentType = "text/csv";

            if (string.Equals(exportType, "event"))
            {
                var attendees = db.EventAttendanceRepository.Get(ev => ev.EventId == id).ToList();
                foreach (var attendee in attendees)
                {
                    var student = db.StudentRepository.GetById(attendee.StudentId);
                    sw.WriteLine(
                        $"\"{student.StudentNumber}\",\"{student.FirstName}\",\"{student.MiddleName}\",\"{student.LastName}\",\"{student.Address1}\"," +
                        $"\"{student.Address2}\",\"{student.ZipCode}\",\"{student.City}\",\"{student.State}\",\"{student.PhoneNumber}\",\"{student.Email}\"," +
                        $"\"{student.BirthDate}\",\"{student.FirstGraduationYear}\",\"{student.SecondGraduationYear}\",\"{student.ThirdGraduationYear}\"," +
                        $"\"{student.ConstituentType}\",\"{student.AllowCommunication}\"");
                }
                Response.Write(sw.ToString());
                Response.End();
            }
            else
            {
                var students = db.StudentRepository.Get();
                foreach (var student in students)
                    sw.WriteLine(
                        $"\"{student.StudentNumber}\",\"{student.FirstName}\",\"{student.MiddleName}\",\"{student.LastName}\",\"{student.Address1}\"," +
                        $"\"{student.Address2}\",\"{student.ZipCode}\",\"{student.City}\",\"{student.State}\",\"{student.PhoneNumber}\",\"{student.Email}\"," +
                        $"\"{student.BirthDate}\",\"{student.FirstGraduationYear}\",\"{student.SecondGraduationYear}\",\"{student.ThirdGraduationYear}\"," +
                        $"\"{student.ConstituentType}\",\"{student.AllowCommunication}\"");
                Response.Write(sw.ToString());
                Response.End();
            }
        }
    }
}

CollegeConnected/Controllers/ConstituentsController.cs
using System;
using System.Linq;
using System.Net;
using System.Text;
using System.Web.Mvc;
using System.Web.Security;
using CollegeConnected.DataLayer;
using CollegeConnected.Models;

namespace CollegeConnected.Controllers
{
    public class ConstituentsController : Controller

    {
        private readonly UnitOfWork db = new UnitOfWork();
        private readonly BaseController sharedOperations = new BaseController();

        public ActionResult Index()
        {
            if (sharedOperations.IsAuthenticated(Request.Cookies[FormsAuthentication.FormsCookieName]))
            {
                var studentList = db.StudentRepository.Get();
                return View(studentList);
            }
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Create()
        {
            if (sharedOperations.IsAuthenticated(Request.Cookies[FormsAuthentication.FormsCookieName]))
                return View();
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(
        [Bind(
            Include =
                "StudentId,StudentNumber,FirstName,MiddleName,LastName,Address1,Address2,ZipCode,City,State,PhoneNumber," +
                "Email,FirstGraduationYear,SecondGraduationYear,ThirdGraduationYear,BirthDate,UpdateTimeStamp,ConstituentType," +
                "AllowCommunication,HasAttendedEvent,EventsAttended"
        )] Constituent student)
        {
            ViewBag.Years = sharedOperations.GenerateGradYearList();
            var rowExists = db.StudentRepository.dbSet.Any(s => s.StudentNumber.Equals(student.StudentNumber));
            try
            {
                if (ModelState.IsValid)
                {
                    if (student.StudentNumber == null)
                    {
                        SetNewConstituentValues(student);
                        return RedirectToAction("Index");
                    }
                    if (!rowExists)
                    {
                        var sb = new StringBuilder("N");
                        student.StudentNumber = sb.Append(student.StudentNumber).ToString();
                        SetNewConstituentValues(student);
                        return RedirectToAction("Index");
                    }
                    ModelState.AddModelError("Error",
                        "This student number already exists in the system. Search for the person from the Home page.");
                    return View(student);
                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError("Error",
                    "An error occurred saving this constituent. If the problem persits, contact your system administrator." +
                    $"Exception: {e}");
            }
            return View(student);
        }

        private void SetNewConstituentValues(Constituent student)
        {
            student.StudentId = Guid.NewGuid();
            student.UpdateTimeStamp = DateTime.Now;
            student.HasAttendedEvent = false;
            student.EventsAttended = 0;
            db.StudentRepository.Insert(student);
            db.Save();
        }

        public ActionResult Edit(Guid? id)
        {
            ViewBag.Years = sharedOperations.GenerateGradYearList();
            if (sharedOperations.IsAuthenticated(Request.Cookies[FormsAuthentication.FormsCookieName]))
            {
                if (id == null)
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                var student = db.StudentRepository.GetById(id);
                if (student == null)
                    return HttpNotFound();
                return View(student);
            }
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(
        [Bind(
            Include =
                "StudentId,StudentNumber,FirstName,MiddleName,LastName,Address1,Address2,ZipCode,City,State,PhoneNumber," +
                "Email,FirstGraduationYear,SecondGraduationYear,ThirdGraduationYear,BirthDate,UpdateTimeStamp,ConstituentType," +
                "AllowCommunication,HasAttendedEvent,EventsAttended"
        )] Constituent student)
        {
            ViewBag.Years = sharedOperations.GenerateGradYearList();
            if (ModelState.IsValid)
            {
                student.UpdateTimeStamp = DateTime.Now;
                db.StudentRepository.Update(student);
                db.Save();
                return RedirectToAction("Index");
            }
            return View(student);
        }

        public ActionResult Delete(Guid? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var student = db.StudentRepository.GetById(id);
            if (student == null)
                return HttpNotFound();
            return View(student);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            if (sharedOperations.IsAuthenticated(Request.Cookies[FormsAuthentication.FormsCookieName]))
            {
                var student = db.StudentRepository.GetById(id);
                db.StudentRepository.Delete(student);
                db.Save();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

CollegeConnected/Views/Constituents/Create.cshtml
@model CollegeConnected.Models.Constituent

@{
    ViewBag.Title = "Create";
}
<h2>Enter the follwing information and click Save</h2>

@using (Html.BeginForm("Create", "Students", FormMethod.Post, new { autocomplete = "off" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationMessage("Error")


    <div class="form-horizontal">
        <h4>* -Required</h4>
        <hr/>
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        <div class="form-group">
            @Html.LabelFor(model => model.StudentNumber, "N Number", new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudentNumber, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.StudentNumber, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, "First Name*", new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.FirstName, "", new {@class = "text-danger"})
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.MiddleName, "Middle Name", new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.MiddleName, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.MiddleName, "", new {@class = "text-danger"})
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.LastName, "Last Name*", new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.LastName, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, "Phone", new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, "Email*", new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Email, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address1, "Address*", new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address1, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Address1, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address2, "Address2", new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address2, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Address2, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, "City*", new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.City, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, "State*", new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.State, "", new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.State, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ZipCode, "Zip Code*", new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.ZipCode, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.ZipCode, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstGraduationYear, "First Graduation Year*", new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.FirstGraduationYear, (IEnumerable<SelectListItem>) ViewBag.Years, "", new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.FirstGraduationYear, "", new {@class = "text-danger"})
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.SecondGraduationYear, "Second Graduation Year", new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.SecondGraduationYear, (IEnumerable<SelectListItem>) ViewBag.Years, "", new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.SecondGraduationYear, "", new {@class = "text-danger"})
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ThirdGraduationYear, "Third Graduation Year", new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ThirdGraduationYear, (IEnumerable<SelectListItem>) ViewBag.Years, "", new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.ThirdGraduationYear, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthDate, "Date of Birth*", new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.BirthDate, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.BirthDate, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConstituentType, "Constituent Type*", new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.ConstituentType, " ", new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.ConstituentType, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AllowCommunication, "Authorize Communication*", new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.AllowCommunication, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.AllowCommunication, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary btn-sm"/>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CollegeConnected/Views/Constituents/Delete.cshtml
@model CollegeConnected.Models.Constituent

@{
    ViewBag.Title = "Delete";
}


<h2>Are you sure you want to delete this constituent?</h2>
<div>
    <hr/>
    <dl class="dl-horizontal">
        <dt>
            @Html.LabelFor(model => model.FirstName, "First Name")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.LabelFor(model => model.LastName, "Last Namer")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.LabelFor(model => model.PhoneNumber, "Phone Number")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.LabelFor(model => model.Email, "Email Address")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.LabelFor(model => model.FirstGraduationYear, "First Graduation Year")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstGraduationYear)
        </dd>

        <dt>
            @Html.LabelFor(model => model.BirthDate, "Date of Birth")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>


    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-primary btn-sm"/> |
            @Html.ActionLink("Back to Constituents", "Index")
        </div>
    }
</div>

CollegeConnected/Views/Constituents/Details.cshtml
@using GridMvc.Html
@model List<CollegeConnected.Models.Student>
@{
    ViewBag.Title = "Details";
}
@{
    Layout = null;
}

<h2>Details</h2>

<div class="code-cut">
    @Html.Grid(Model).Columns(columns =>
    {
        columns.Add(c => c.StudentNumber).Titled("N Number").Filterable(true);
        columns.Add(c => c.FirstName).Titled("First Name").Filterable(true);
        columns.Add()
            .Encoded(false)
            .Sanitized(false)
            .SetWidth(30)
            .RenderValueAs(o => Html.ActionLink("Edit", "Edit", new {id = o.StudentNumber}));
    }).WithPaging(10).Sortable(true)
</div>

<p>
    @Html.ActionLink("Back to List", "Index")
</p>

CollegeConnected/Views/Constituents/Edit.cshtml
@model CollegeConnected.Models.Constituent

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Constituent</h2>

@Html.Partial("ConfirmStudentPartial")


<div>
    @Html.ActionLink("Back to Constituents", "Index")
</div>

CollegeConnected/Views/Constituents/EditPage.cshtml
@model CollegeConnected.Models.Student

@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>View</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Student</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.StudentId)

        <div class="form-group">
            @Html.LabelFor(model => model.StudentNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudentNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StudentNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MiddleName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MiddleName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MiddleName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ZipCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ZipCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ZipCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GraduationYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GraduationYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GraduationYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BirthDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UpdateTimeStamp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UpdateTimeStamp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UpdateTimeStamp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CollegeConnected/Views/Constituents/Index.cshtml
@using GridMvc.Html
@model IEnumerable<CollegeConnected.Models.Constituent>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Constituents</h2>
<p> @Html.ActionLink("Export Constituent Data", "ExportToCsv", "Base", new {exportType = "student"}, new {@class = "btn btn-primary btn-sm"})</p>

@Html.Grid(Model).Columns(columns =>
{
    columns.Add(model => model.ConstituentType).Titled("Constituent Type").Sortable(true).SetWidth(200).Filterable(true);
    columns.Add(model => model.FirstName).Titled("First Name").Filterable(true).Sortable(true).SetWidth(150);
    columns.Add(model => model.LastName).Titled("Last Name").Filterable(true).Sortable(true).SetWidth(110);
    columns.Add(model => model.PhoneNumber).Titled("Phone").Filterable(true).Sortable(true).SetWidth(110);
    columns.Add(model => model.Email).Titled("Email").Filterable(true).Sortable(true).SetWidth(200);
    columns.Add(model => model.State).Titled("State").Filterable(true).Sortable(true).SetWidth(110);
    columns.Add(model => model.FirstGraduationYear).Titled("Graduation Year").Filterable(true).Sortable(true).SetWidth(100);
    columns.Add(model => model.AllowCommunication).Titled("Allow Communication").Filterable(true).Sortable(true).SetWidth(30);
    columns.Add().Encoded(false).Sanitized(false).SetWidth(30).RenderValueAs(model => Html.ActionLink("Edit", "Edit", "Constituents", new {id = model.StudentId}, new {@class = "btn btn-primary btn-sm"}));
    columns.Add().Encoded(false).Sanitized(false).SetWidth(30).RenderValueAs(model => Html.ActionLink("Delete", "Delete", "Constituents", new {id = model.StudentId}, new {@class = "btn btn-primary btn-sm"}));
}).WithPaging(15)